# Generated by Django 4.0.3 on 2022-04-19 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='missing_people'),
        ),
        migrations.AddField(
            model_name='post',
            name='last_seen_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='last_seen_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
